### ISSUE TITLE
Train Qwen-Image-Edit OOM

### ISSUE THREAD

**Issue by yinian-lw** [Saquib764/omini-kontext#38]
setting:
```
lora_rank:16
lora_alpha:16
target_size: 576, 768
reference_size: 512, 512
```
CUDA OOM

**Comment by Saquib764** [comment]
I use H200 with 141 GB VRAM without any error. However, do not train Qwen Image Edit. I haven’t been able to get a good model. Seems like there is some issue with diffuser’s implementation. 
See - https://github.com/huggingface/diffusers/issues/12216#issuecomment-3218294613

**Comment by yinian-lw** [comment]
> I use H200 with 141 GB VRAM without any error. However, do not train Qwen Image Edit. I haven’t been able to get a good model. Seems like there is some issue with diffuser’s implementation. See - [huggingface/diffusers#12216 (comment)](https://github.com/huggingface/diffusers/issues/12216#issuecomment-3218294613)

I got OOM when using H100 with 80GB VRAM, but training with gradient_checkpointing enabled works. By the way, there is a bug in gradient_checkpointing, which is missing ```self.transformer.enable_gradient_checkpointing()```

**Comment by xuxinda** [comment]
> > I use H200 with 141 GB VRAM without any error. However, do not train Qwen Image Edit. I haven’t been able to get a good model. Seems like there is some issue with diffuser’s implementation. See - [huggingface/diffusers#12216 (comment)](https://github.com/huggingface/diffusers/issues/12216#issuecomment-3218294613)
> 
> I got OOM when using H100 with 80GB VRAM, but training with gradient_checkpointing enabled works. By the way, there is a bug in gradient_checkpointing, which is missing `self.transformer.enable_gradient_checkpointing()`

error like this?  how do you solve it?
```
    encoder_hidden_states, hidden_states = self._gradient_checkpointing_func(
TypeError: 'NoneType' object is not callable
```

**Comment by xuxinda** [comment]
> > > I use H200 with 141 GB VRAM without any error. However, do not train Qwen Image Edit. I haven’t been able to get a good model. Seems like there is some issue with diffuser’s implementation. See - [huggingface/diffusers#12216 (comment)](https://github.com/huggingface/diffusers/issues/12216#issuecomment-3218294613)
> > 
> > 
> > I got OOM when using H100 with 80GB VRAM, but training with gradient_checkpointing enabled works. By the way, there is a bug in gradient_checkpointing, which is missing `self.transformer.enable_gradient_checkpointing()`
> 
> error like this? how do you solve it?
> 
> ```
>     encoder_hidden_states, hidden_states = self._gradient_checkpointing_func(
> TypeError: 'NoneType' object is not callable
> ```

@Saquib764 @yinian-lw Maybe changing the code will solve it. I made the changes and now it works without any errors.
in `src\train\model.py` 38 line
```
# self.transformer.gradient_checkpointing = gradient_checkpointing
self.transformer.enable_gradient_checkpointing()
```

**Comment by Saquib764** [comment]
done. It should work fine now
